In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings("ignore")

In [2]:
telecom=pd.read_csv("telecom_churn.csv")

In [3]:
telecom.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
telecom.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
telecom["TotalCharges"].isnull().sum()

0

In [6]:
telecom["TotalCharges"].value_counts()

          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: TotalCharges, Length: 6531, dtype: int64

In [7]:
telecom["TotalCharges"].replace(" ",np.nan,inplace=True)

In [8]:
telecom["TotalCharges"].value_counts()

20.2      11
19.75      9
20.05      8
19.9       8
19.65      8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: TotalCharges, Length: 6530, dtype: int64

In [9]:
telecom["TotalCharges"].isnull().sum()*100/telecom.shape[0]

0.15618344455487718

In [10]:
telecom["TotalCharges"]=telecom["TotalCharges"].astype("float")

In [11]:
telecom["TotalCharges"].fillna(telecom["TotalCharges"].mean(),inplace=True)

In [12]:
#separate all object type data and hold in df_cat
telecom_cat = telecom.select_dtypes("object")
#separate all numeric datatype type data and hold in df_num
telecom_num=telecom.select_dtypes(["float64","int64"])

In [13]:
from sklearn.preprocessing import LabelEncoder
for col in telecom_cat:
    #create object of LabelEncoder
    le=LabelEncoder()
    telecom_cat[col] = le.fit_transform(telecom_cat[[col]])

In [14]:
telecom_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   int32
 1   gender            7043 non-null   int32
 2   Partner           7043 non-null   int32
 3   Dependents        7043 non-null   int32
 4   PhoneService      7043 non-null   int32
 5   MultipleLines     7043 non-null   int32
 6   InternetService   7043 non-null   int32
 7   OnlineSecurity    7043 non-null   int32
 8   OnlineBackup      7043 non-null   int32
 9   DeviceProtection  7043 non-null   int32
 10  TechSupport       7043 non-null   int32
 11  StreamingTV       7043 non-null   int32
 12  StreamingMovies   7043 non-null   int32
 13  Contract          7043 non-null   int32
 14  PaperlessBilling  7043 non-null   int32
 15  PaymentMethod     7043 non-null   int32
 16  Churn             7043 non-null   int32
dtypes: int32(17)
memory usage: 467.8 

In [15]:
telecom_new = pd.concat([telecom_num,telecom_cat],axis=1)
telecom_new.head()

SeniorCitizen  tenure  MonthlyCharges  TotalCharges  customerID  gender  \
0              0       1           29.85         29.85        5375       0   
1              0      34           56.95       1889.50        3962       1   
2              0       2           53.85        108.15        2564       1   
3              0      45           42.30       1840.75        5535       1   
4              0       2           70.70        151.65        6511       0   

   Partner  Dependents  PhoneService  MultipleLines  ...  OnlineSecurity  \
0        1           0             0              1  ...               0   
1        0           0             1              0  ...               2   
2        0           0             1              0  ...               2   
3        0           0             0              1  ...               2   
4        0           0             1              0  ...               0   

   OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0             2                 0            0            0                0   
1             0                 2            0            0                0   
2             2                 0            0            0                0   
3             0                 2            2            0                0   
4             0                 0            0            0                0   

   Contract  PaperlessBilling  PaymentMethod  Churn  
0         0                 1              2      0  
1         1                 0              3      0  
2         0                 1              3      1  
3         1                 0              0      0  
4         0                 1              2      1  

[5 rows x 21 columns]

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
X=telecom_new.drop("Churn",axis=1) #input variable
Y=telecom_new["Churn"] #output means target

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [19]:
pd.Series(Y_train).value_counts()

0    3589
1    1341
Name: Churn, dtype: int64

In [20]:
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [21]:
from imblearn.over_sampling import RandomOverSampler

In [22]:
ros=RandomOverSampler()

In [23]:
X_train1,Y_train1=ros.fit_resample(X_train,Y_train)

In [24]:
X_test1,Y_test1=ros.fit_resample(X_test,Y_test)

In [25]:
pd.Series(Y_train1).value_counts()

0    3589
1    3589
Name: Churn, dtype: int64

In [26]:
def create_model(model):
    model.fit(X_train1,Y_train1)
    Y_pred=model.predict(X_test1)
    print("Classification report")
    print(classification_report(Y_test1,Y_pred))
    print("Confusion Matrix")
    print(confusion_matrix(Y_test1,Y_pred))
    return model

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [28]:
lr=LogisticRegression()

In [29]:
lr=create_model(lr)

Classification report
              precision    recall  f1-score   support

           0       0.82      0.74      0.78      1585
           1       0.76      0.84      0.80      1585

    accuracy                           0.79      3170
   macro avg       0.79      0.79      0.79      3170
weighted avg       0.79      0.79      0.79      3170

Confusion Matrix
[[1167  418]
 [ 258 1327]]


In [30]:
from sklearn.tree import DecisionTreeClassifier

In [31]:
dt=DecisionTreeClassifier()

In [32]:
dt=create_model(dt)

Classification report
              precision    recall  f1-score   support

           0       0.65      0.81      0.72      1585
           1       0.74      0.56      0.64      1585

    accuracy                           0.68      3170
   macro avg       0.69      0.68      0.68      3170
weighted avg       0.69      0.68      0.68      3170

Confusion Matrix
[[1283  302]
 [ 705  880]]


In [33]:
dt1=DecisionTreeClassifier(max_depth=8)

In [34]:
dt1=create_model(dt1)

Classification report
              precision    recall  f1-score   support

           0       0.76      0.73      0.75      1585
           1       0.74      0.77      0.76      1585

    accuracy                           0.75      3170
   macro avg       0.75      0.75      0.75      3170
weighted avg       0.75      0.75      0.75      3170

Confusion Matrix
[[1160  425]
 [ 360 1225]]


In [35]:
dt2=DecisionTreeClassifier(min_samples_leaf=50)

In [36]:
dt2=create_model(dt2)

Classification report
              precision    recall  f1-score   support

           0       0.78      0.73      0.75      1585
           1       0.75      0.79      0.77      1585

    accuracy                           0.76      3170
   macro avg       0.76      0.76      0.76      3170
weighted avg       0.76      0.76      0.76      3170

Confusion Matrix
[[1155  430]
 [ 326 1259]]


In [37]:
dt3=DecisionTreeClassifier(criterion="entropy",min_samples_leaf=50)

In [38]:
dt3=create_model(dt3)

Classification report
              precision    recall  f1-score   support

           0       0.79      0.74      0.76      1585
           1       0.75      0.80      0.78      1585

    accuracy                           0.77      3170
   macro avg       0.77      0.77      0.77      3170
weighted avg       0.77      0.77      0.77      3170

Confusion Matrix
[[1170  415]
 [ 316 1269]]


In [39]:
from sklearn.ensemble import VotingClassifier

In [40]:
lr=LogisticRegression()
dt=DecisionTreeClassifier()
dt1=DecisionTreeClassifier(criterion="entropy",min_samples_leaf=50)

In [41]:
model_list=[("LogisticRegression",lr),("DecisionTreeClassifier",dt),("DecisionTreeClassifierwithentropy",dt1)]

In [42]:
vc=VotingClassifier(estimators=model_list)

In [43]:
vc=create_model(vc)

Classification report
              precision    recall  f1-score   support

           0       0.80      0.76      0.78      1585
           1       0.77      0.81      0.79      1585

    accuracy                           0.78      3170
   macro avg       0.78      0.78      0.78      3170
weighted avg       0.78      0.78      0.78      3170

Confusion Matrix
[[1203  382]
 [ 307 1278]]


In [44]:
vc1=VotingClassifier(estimators=model_list,voting="soft")

In [45]:
vc1=create_model(vc1)

Classification report
              precision    recall  f1-score   support

           0       0.74      0.80      0.77      1585
           1       0.78      0.72      0.75      1585

    accuracy                           0.76      3170
   macro avg       0.76      0.76      0.76      3170
weighted avg       0.76      0.76      0.76      3170

Confusion Matrix
[[1269  316]
 [ 445 1140]]


In [46]:
from sklearn.ensemble import BaggingClassifier

In [47]:
bc=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=7043,random_state=1)

In [48]:
bc=create_model(bc)

Classification report
              precision    recall  f1-score   support

           0       0.82      0.74      0.78      1585
           1       0.76      0.84      0.80      1585

    accuracy                           0.79      3170
   macro avg       0.79      0.79      0.79      3170
weighted avg       0.79      0.79      0.79      3170

Confusion Matrix
[[1166  419]
 [ 257 1328]]


In [49]:
bc1=BaggingClassifier(LogisticRegression(),n_estimators=10,max_samples=7043,random_state=1,bootstrap=False)

In [50]:
bc1=create_model(bc1)

Classification report
              precision    recall  f1-score   support

           0       0.82      0.74      0.77      1585
           1       0.76      0.83      0.79      1585

    accuracy                           0.78      3170
   macro avg       0.79      0.78      0.78      3170
weighted avg       0.79      0.78      0.78      3170

Confusion Matrix
[[1166  419]
 [ 263 1322]]


In [51]:
bc2=BaggingClassifier(DecisionTreeClassifier(),n_estimators=10,max_samples=7043,random_state=1) #RandomForestTree

In [52]:
bc2=create_model(bc2) 

Classification report
              precision    recall  f1-score   support

           0       0.67      0.86      0.75      1585
           1       0.80      0.58      0.67      1585

    accuracy                           0.72      3170
   macro avg       0.74      0.72      0.71      3170
weighted avg       0.74      0.72      0.71      3170

Confusion Matrix
[[1361  224]
 [ 672  913]]


In [53]:
from sklearn.ensemble import AdaBoostClassifier

In [54]:
ada=AdaBoostClassifier(n_estimators=75)

In [55]:
ada=create_model(ada)

Classification report
              precision    recall  f1-score   support

           0       0.80      0.72      0.76      1585
           1       0.75      0.81      0.78      1585

    accuracy                           0.77      3170
   macro avg       0.77      0.77      0.77      3170
weighted avg       0.77      0.77      0.77      3170

Confusion Matrix
[[1149  436]
 [ 296 1289]]


In [56]:
from sklearn.ensemble import GradientBoostingClassifier

In [57]:
gb=GradientBoostingClassifier(n_estimators=75)

In [58]:
gb=create_model(gb)

Classification report
              precision    recall  f1-score   support

           0       0.81      0.74      0.77      1585
           1       0.76      0.83      0.79      1585

    accuracy                           0.78      3170
   macro avg       0.78      0.78      0.78      3170
weighted avg       0.78      0.78      0.78      3170

Confusion Matrix
[[1169  416]
 [ 274 1311]]


In [59]:
from xgboost import XGBClassifier

In [60]:
xgb=XGBClassifier(n_estimators=75,reg_alpha=1)

In [61]:
xgb=create_model(xgb)

[15:50:15] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
Classification report
              precision    recall  f1-score   support

           0       0.73      0.81      0.77      1585
           1       0.78      0.70      0.74      1585

    accuracy                           0.75      3170
   macro avg       0.76      0.75      0.75      3170
weighted avg       0.76      0.75      0.75      3170

Confusion Matrix
[[1279  306]
 [ 476 1109]]


In [62]:
from mlxtend.classifier import StackingClassifier

In [63]:
model_list=[lr,dt,dt1]

In [64]:
meta=LogisticRegression()

In [65]:
sc=StackingClassifier(model_list,meta)

In [66]:
sc=create_model(sc)

Classification report
              precision    recall  f1-score   support

           0       0.64      0.81      0.72      1585
           1       0.74      0.55      0.63      1585

    accuracy                           0.68      3170
   macro avg       0.69      0.68      0.68      3170
weighted avg       0.69      0.68      0.68      3170

Confusion Matrix
[[1283  302]
 [ 710  875]]


In [67]:
from sklearn.naive_bayes import GaussianNB

In [68]:
gnb=GaussianNB()

In [69]:
from sklearn.neighbors import KNeighborsClassifier

In [70]:
knc=KNeighborsClassifier(n_neighbors=7,metric="minkowski",p=2)

In [71]:
knc=create_model(knc)

Classification report
              precision    recall  f1-score   support

           0       0.76      0.66      0.70      1585
           1       0.70      0.79      0.74      1585

    accuracy                           0.72      3170
   macro avg       0.73      0.72      0.72      3170
weighted avg       0.73      0.72      0.72      3170

Confusion Matrix
[[1040  545]
 [ 335 1250]]


In [72]:
from sklearn.svm import  LinearSVC

In [73]:
svm=LinearSVC(random_state=1)

In [74]:
svm=create_model(svm)

Classification report
              precision    recall  f1-score   support

           0       0.83      0.73      0.77      1585
           1       0.76      0.85      0.80      1585

    accuracy                           0.79      3170
   macro avg       0.79      0.79      0.79      3170
weighted avg       0.79      0.79      0.79      3170

Confusion Matrix
[[1153  432]
 [ 242 1343]]


In [75]:
from sklearn.svm import LinearSVC
from sklearn.svm import SVC

In [76]:
svm1=LinearSVC(random_state=1,C=0.08)

In [77]:
svm1=create_model(svm1)

Classification report
              precision    recall  f1-score   support

           0       0.83      0.73      0.77      1585
           1       0.76      0.85      0.80      1585

    accuracy                           0.79      3170
   macro avg       0.79      0.79      0.79      3170
weighted avg       0.79      0.79      0.79      3170

Confusion Matrix
[[1153  432]
 [ 240 1345]]


In [78]:
poly_svc=SVC(random_state=1,kernel="poly")

In [79]:
poly_svc=create_model(poly_svc)

Classification report
              precision    recall  f1-score   support

           0       0.78      0.73      0.76      1585
           1       0.75      0.79      0.77      1585

    accuracy                           0.76      3170
   macro avg       0.76      0.76      0.76      3170
weighted avg       0.76      0.76      0.76      3170

Confusion Matrix
[[1162  423]
 [ 331 1254]]


In [80]:
rbf=SVC(random_state=1,kernel="rbf")

In [81]:
rbf=create_model(rbf)

Classification report
              precision    recall  f1-score   support

           0       0.79      0.75      0.77      1585
           1       0.76      0.80      0.78      1585

    accuracy                           0.77      3170
   macro avg       0.77      0.77      0.77      3170
weighted avg       0.77      0.77      0.77      3170

Confusion Matrix
[[1194  391]
 [ 324 1261]]
